initial snapshot does not define collation info
cakephp/migrations pull request #645
Opened 2023-10-03 17:24 UTC by rrd108

This PR is intended to fix #2225

The added test case passes, so it seems to be fine for me.

However, thi is not a final version as I was not sure about 2 things.

# Question 1

The current solution actually execute the `migration_snapshot` command and creates and writes a new migration file. My guess is that I could do it without creating the file, but I did not find out how.

# Question 2

The current test alters the `articles` table's `title` field's collation. So I guess I have to alter it back to avoid affecting other tests. Do I have to do it, or the test system will drop the table after each tests?

2023-10-03 17:41 UTC, rrd108 commented
I see, I have to handle the case when the collation is the default. I will get back to it in a few days.

2023-10-03 18:21 UTC, ndm2 commented
Please compare against the full snapshot like the other snapshot tests do, ideally use `runSnapshotTest()`, see for example the `testSnapshotWithAutoIdCompatibleSignedPrimaryKeys()` test.

The comparison file would be `tests/comparisons/Migration/test_snapshot_with_non_default_collation.php`. And then also please register that comparison file with `MigrationsTest::migrationsProvider()`, that way it will be tested whether the generated snapshot can be applied without errors.

As can be seen from the failing tests, this would affect diffs too, so encoding defaults and changes would need to be properly tested there too.

Might sound a bit pedantic, but when my recent work on Migrations taught me anything, then that its sloppy testing is one of its worst enemies, and a major source of pain when making changes.

2023-10-05 16:32 UTC, rrd108 commented
I still have to fix what @ndm2 suggested.

What about my question 2?

2023-10-10 05:30 UTC, rrd108 commented
Do I have to do anything more on this?

2023-10-10 05:43 UTC, LordSimal approved these changes
LGTM

2023-10-10 14:08 UTC, ndm2 requested changes
Please also add the new snapshot to `\Migrations\Test\TestCase\MigrationsTest::migrationsProvider()`.

2023-10-10 14:08 UTC, ndm2 commented on tests/comparisons/Diff/addRemove/the_diff_add_remove_mysql.php
> +                'collation' => 'utf8_general_ci',
This is the same as the default collation. This being here seems inconsistent with the snapshot behavior. Same for the other diff. It's also inconsistent with itself when a table is being dropped and then recreated, for example the `tags` table in the `default` diff, when recreated in `down()` it has no `collation` option set.

We should probably also cover the case where the comparison schema (the `.lock` file) has tables with columns using non-default collations.

2023-10-10 14:08 UTC, ndm2 commented on tests/TestCase/Command/BakeMigrationSnapshotCommandTest.php
> +        $connection->execute('ALTER TABLE articles MODIFY title VARCHAR(255) CHARACTER SET utf8 COLLATE utf8mb3_hungarian_ci');
This should be reset afterwards. Verify it by temporarily placing this test before the other snapshot tests. Also note that it removes the comment from the column.

2023-10-10 14:24 UTC, ndm2 commented
So I just realized that `\Migrations\Test\TestCase\MigrationsTest::testMigrateSnapshots()` is actually still broken and not testing properly. That would also affect this snapshot right here, which as a foreign key for a non-existent table.

I'll try to get that fixed somewhat quickly.

2023-10-11 09:12 UTC, rrd108 commented
> Please also add the new snapshot to `\Migrations\Test\TestCase\MigrationsTest::migrationsProvider()`.

added in 9052c29

2023-10-17 08:12 UTC, rrd108 commented on tests/TestCase/Command/BakeMigrationSnapshotCommandTest.php
> +        $connection->execute('ALTER TABLE articles MODIFY title VARCHAR(255) CHARACTER SET utf8 COLLATE utf8mb3_hungarian_ci');
If I have to reset afterwards, I would just create a new table if you are ok with it. So it will have no effect on any other tests.

2023-10-28 10:51 UTC, rrd108 commented on tests/comparisons/Diff/addRemove/the_diff_add_remove_mysql.php
> +                'collation' => 'utf8_general_ci',
Is it connected to your later comment https://github.com/cakephp/migrations/pull/645#issuecomment-1755534423 ?

Or is it something what I should fix somehow?

2023-10-30 17:07 UTC, rrd108 commented on tests/comparisons/Diff/addRemove/the_diff_add_remove_mysql.php
> +                'collation' => 'utf8_general_ci',
@ndm2  I am waiting for your reply

2023-10-31 12:35 UTC, ndm2 commented on tests/comparisons/Diff/addRemove/the_diff_add_remove_mysql.php
> +                'collation' => 'utf8_general_ci',
> Is it connected to your later comment [#645 (comment)](https://github.com/cakephp/migrations/pull/645#issuecomment-1755534423) ?

No, that was just about none of the snapshot apply testing working. I've pushed [a fix](https://github.com/cakephp/migrations/pull/648) for it. This PR will need to be rebased accordingly.

> Or is it something what I should fix somehow?

I think so. You've made changes to specifically handle the case where the collation matches the default collation, but this doesn't seem to be applied consistently, as the `collation` option is present here, despite that being the table's default collation.

2023-11-02 09:39 UTC, rrd108 commented on tests/comparisons/Diff/addRemove/the_diff_add_remove_mysql.php
> +                'collation' => 'utf8_general_ci',
Ok. They do not really have anything with my fix. 
Done in fde1fb325a7f5aea1146f91464cf581bfbd53575

2023-11-02 10:23 UTC, rrd108 commented
@ndm2 As I see tha failing tests coming from other test, not related to this one.

2023-11-02 11:17 UTC, ndm2 commented
I'm note sure what exactly you did, but it looks like rebasing somehow went wrong, all the changes here from existing commits should not be seen as new. The test failures might be a result of that.

2023-11-02 12:47 UTC, rrd108 commented
> I'm note sure what exactly you did, but it looks like rebasing somehow went wrong, all the changes here from existing commits should not be seen as new. The test failures might be a result of that.

I recloned the repo

> I'm note sure what exactly you did, but it looks like rebasing somehow went wrong, all the changes here from existing commits should not be seen as new. The test failures might be a result of that.

I do not know what did I do wrong.

Anyway I would need some suggestion how to move forward.

I cloned cakephp/migrations to my dev machine and executed `vendor/bin/phpunit tests` without any changes and I get `Tests: 122, Assertions: 396, Errors: 8, Warnings: 1, Skipped: 10`

So it seems that is the starting point for now. 

Re-adding my changes to this newly cloned repo does not change the number of errors, so I guess my additions are ok, but the checks will certainly fail.

2023-11-02 13:00 UTC, rrd108 commented
anyway it seems no errors on the pilenine.

2023-11-02 22:48 UTC, dereuromark commented
I wonder if this could be squash merged 
But it would be safer to squash and rebase Prior to merging

2023-11-03 13:57 UTC, closed without merging